### ISSUE TITLE
Set Functions Should Set Width and Height Parameters

### ISSUE THREAD

**Issue by xsk8rat** [sparkfun/SparkFun_SSD1320_OLED_Arduino_Library#3]
Small change to prevent compile time errors. These two functions (setDisplayHeight and setDisplayWidth) were declared as void, but were returning values instead of setting them. Typos really.

New versions:

void SSD1320::setDisplayWidth(uint16_t W) {
  _displayWidth = W;
}

void SSD1320::setDisplayHeight(uint16_t H) {
  _displayHeight = H;
}

**Comment by nseidle** [comment]
Good catch! Can you send me a PR?

**Comment by nseidle** [comment]
Pulled in to v1.0.4 https://github.com/sparkfun/SparkFun_SSD1320_OLED_Arduino_Library/releases/tag/v1.0.4

**Comment by nseidle** [comment]
Thanks for your help!
