### ISSUE TITLE
Can't set color

### ISSUE THREAD

**Issue by Vasile-Peste** [sparkfun/SparkFun_SSD1320_OLED_Arduino_Library#5]
Hi, the display is awesome. Using the library I can't set a color different than WHITE or BLACK. Also I looked at your library and I found something strange. Sorry for my confusion.

```cpp
// SSD1320_OLED.h
#define BLACK 0
#define WHITE 1
```

Black should be 0 and white 255 or am I wrong?

```cpp
// SSD1320_OLED.cpp
/** \brief Set color.
    Set the current draw's color. Only WHITE and BLACK available.
*/
void SSD1320::setColor(uint8_t color) {
  foreColor = color;
}
```

Why I can't set a color different than white or black?
In the README.md of this repository you have as an example an image loaded with different shades of black and white, why I can't use these colors? Sorry again for my confusion.

By the way, this is a video of your display in action with PONG: https://youtu.be/sQk5tUnh5TU.
Waiting for a bigger one, thank you.

**Comment by nseidle** [comment]
Nice video! Thank you for recording it!

To clarify, the OLED is monochrome so there is no 'color' per se, just On/Off pixels. The display *does* support 4-bit grayscale but this library [is memory limited](https://github.com/sparkfun/SparkFun_SSD1320_OLED_Arduino_Library/blob/master/src/SSD1320_OLED.cpp#L40) to only support 1-bit (on/off).

The `#define WHITE 1` is arbitrary and used as a [check in setPixel()](https://github.com/sparkfun/SparkFun_SSD1320_OLED_Arduino_Library/blob/master/src/SSD1320_OLED.cpp#L694).

Grayscale is possible but requires a larger amount of RAM (perhaps a Teensy could do it). The grayscale example uses the [JPEG to 4-bit BMP script](https://github.com/sparkfun/BMPtoArray) to generate a static array. This array can be sent over serial or can be stored in ProgMem but there's not enough RAM on the Uno to store a frame buffer of 4-bits for the entire display.
